<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Administrativo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Administrativo_model');
    } 

    /*
     * Listing of administrativo
     */
    function index()
    {
        $data['administrativo'] = $this->Administrativo_model->get_all_administrativo();
        
        $data['_view'] = 'administrativo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new administrativo
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('administrativo_nombre','Administrativo Nombre','required');
		$this->form_validation->set_rules('administrativo_apellidos','Administrativo Apellidos','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'estado_id' => $this->input->post('estado_id'),
				'estadocivil_id' => $this->input->post('estadocivil_id'),
				'institucion_id' => $this->input->post('institucion_id'),
				'genero_id' => $this->input->post('genero_id'),
				'administrativo_nombre' => $this->input->post('administrativo_nombre'),
				'administrativo_apellidos' => $this->input->post('administrativo_apellidos'),
				'administrativo_fechanac' => $this->input->post('administrativo_fechanac'),
				'administrativo_edad' => $this->input->post('administrativo_edad'),
				'administrativo_ci' => $this->input->post('administrativo_ci'),
				'administrativo_extci' => $this->input->post('administrativo_extci'),
				'administrativo_codigo' => $this->input->post('administrativo_codigo'),
				'administrativo_direccion' => $this->input->post('administrativo_direccion'),
				'administrativo_telefono' => $this->input->post('administrativo_telefono'),
				'administrativo_celular' => $this->input->post('administrativo_celular'),
				'administrativo_cargo' => $this->input->post('administrativo_cargo'),
				'administrativo_foto' => $this->input->post('administrativo_foto'),
				'administrativo_fechareg' => $this->input->post('administrativo_fechareg'),
            );
            
            $administrativo_id = $this->Administrativo_model->add_administrativo($params);
            redirect('administrativo/index');
        }
        else
        {
			$this->load->model('Estado_model');
			$data['all_estado'] = $this->Estado_model->get_all_estado();

			$this->load->model('Estado_civil_model');
			$data['all_estado_civil'] = $this->Estado_civil_model->get_all_estado_civil();

			$this->load->model('Institucion_model');
			$data['all_institucion'] = $this->Institucion_model->get_all_institucion();

			$this->load->model('Genero_model');
			$data['all_genero'] = $this->Genero_model->get_all_genero();
            
            $data['_view'] = 'administrativo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a administrativo
     */
    function edit($administrativo_id)
    {   
        // check if the administrativo exists before trying to edit it
        $data['administrativo'] = $this->Administrativo_model->get_administrativo($administrativo_id);
        
        if(isset($data['administrativo']['administrativo_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('administrativo_nombre','Administrativo Nombre','required');
			$this->form_validation->set_rules('administrativo_apellidos','Administrativo Apellidos','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'estado_id' => $this->input->post('estado_id'),
					'estadocivil_id' => $this->input->post('estadocivil_id'),
					'institucion_id' => $this->input->post('institucion_id'),
					'genero_id' => $this->input->post('genero_id'),
					'administrativo_nombre' => $this->input->post('administrativo_nombre'),
					'administrativo_apellidos' => $this->input->post('administrativo_apellidos'),
					'administrativo_fechanac' => $this->input->post('administrativo_fechanac'),
					'administrativo_edad' => $this->input->post('administrativo_edad'),
					'administrativo_ci' => $this->input->post('administrativo_ci'),
					'administrativo_extci' => $this->input->post('administrativo_extci'),
					'administrativo_codigo' => $this->input->post('administrativo_codigo'),
					'administrativo_direccion' => $this->input->post('administrativo_direccion'),
					'administrativo_telefono' => $this->input->post('administrativo_telefono'),
					'administrativo_celular' => $this->input->post('administrativo_celular'),
					'administrativo_cargo' => $this->input->post('administrativo_cargo'),
					'administrativo_foto' => $this->input->post('administrativo_foto'),
					'administrativo_fechareg' => $this->input->post('administrativo_fechareg'),
                );

                $this->Administrativo_model->update_administrativo($administrativo_id,$params);            
                redirect('administrativo/index');
            }
            else
            {
				$this->load->model('Estado_model');
				$data['all_estado'] = $this->Estado_model->get_all_estado();

				$this->load->model('Estado_civil_model');
				$data['all_estado_civil'] = $this->Estado_civil_model->get_all_estado_civil();

				$this->load->model('Institucion_model');
				$data['all_institucion'] = $this->Institucion_model->get_all_institucion();

				$this->load->model('Genero_model');
				$data['all_genero'] = $this->Genero_model->get_all_genero();

                $data['_view'] = 'administrativo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The administrativo you are trying to edit does not exist.');
    } 

    /*
     * Deleting administrativo
     */
    function remove($administrativo_id)
    {
        $administrativo = $this->Administrativo_model->get_administrativo($administrativo_id);

        // check if the administrativo exists before trying to delete it
        if(isset($administrativo['administrativo_id']))
        {
            $this->Administrativo_model->delete_administrativo($administrativo_id);
            redirect('administrativo/index');
        }
        else
            show_error('The administrativo you are trying to delete does not exist.');
    }
    
}
