<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Area_materium extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Area_materium_model');
    } 

    /*
     * Listing of area_materia
     */
    function index()
    {
        $data['area_materia'] = $this->Area_materium_model->get_all_area_materia();
        
        $data['_view'] = 'area_materium/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new area_materium
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'area_nombre' => $this->input->post('area_nombre'),
				'area_fechareg' => $this->input->post('area_fechareg'),
            );
            
            $area_materium_id = $this->Area_materium_model->add_area_materium($params);
            redirect('area_materium/index');
        }
        else
        {            
            $data['_view'] = 'area_materium/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a area_materium
     */
    function edit($area_id)
    {   
        // check if the area_materium exists before trying to edit it
        $data['area_materium'] = $this->Area_materium_model->get_area_materium($area_id);
        
        if(isset($data['area_materium']['area_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'area_nombre' => $this->input->post('area_nombre'),
					'area_fechareg' => $this->input->post('area_fechareg'),
                );

                $this->Area_materium_model->update_area_materium($area_id,$params);            
                redirect('area_materium/index');
            }
            else
            {
                $data['_view'] = 'area_materium/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The area_materium you are trying to edit does not exist.');
    } 

    /*
     * Deleting area_materium
     */
    function remove($area_id)
    {
        $area_materium = $this->Area_materium_model->get_area_materium($area_id);

        // check if the area_materium exists before trying to delete it
        if(isset($area_materium['area_id']))
        {
            $this->Area_materium_model->delete_area_materium($area_id);
            redirect('area_materium/index');
        }
        else
            show_error('The area_materium you are trying to delete does not exist.');
    }
    
}
