<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Factura extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Factura_model');
    } 

    /*
     * Listing of factura
     */
    function index()
    {
        $data['factura'] = $this->Factura_model->get_all_factura();
        
        $data['_view'] = 'factura/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new factura
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'matricula_id' => $this->input->post('matricula_id'),
				'mensualidad_id' => $this->input->post('mensualidad_id'),
            );
            
            $factura_id = $this->Factura_model->add_factura($params);
            redirect('factura/index');
        }
        else
        {
			$this->load->model('Matricula_model');
			$data['all_matricula'] = $this->Matricula_model->get_all_matricula();

			$this->load->model('Mensualidad_model');
			$data['all_mensualidad'] = $this->Mensualidad_model->get_all_mensualidad();
            
            $data['_view'] = 'factura/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a factura
     */
    function edit($factura_id)
    {   
        // check if the factura exists before trying to edit it
        $data['factura'] = $this->Factura_model->get_factura($factura_id);
        
        if(isset($data['factura']['factura_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'matricula_id' => $this->input->post('matricula_id'),
					'mensualidad_id' => $this->input->post('mensualidad_id'),
                );

                $this->Factura_model->update_factura($factura_id,$params);            
                redirect('factura/index');
            }
            else
            {
				$this->load->model('Matricula_model');
				$data['all_matricula'] = $this->Matricula_model->get_all_matricula();

				$this->load->model('Mensualidad_model');
				$data['all_mensualidad'] = $this->Mensualidad_model->get_all_mensualidad();

                $data['_view'] = 'factura/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The factura you are trying to edit does not exist.');
    } 

    /*
     * Deleting factura
     */
    function remove($factura_id)
    {
        $factura = $this->Factura_model->get_factura($factura_id);

        // check if the factura exists before trying to delete it
        if(isset($factura['factura_id']))
        {
            $this->Factura_model->delete_factura($factura_id);
            redirect('factura/index');
        }
        else
            show_error('The factura you are trying to delete does not exist.');
    }
    
}
