<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Grupo extends CI_Controller{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
        $this->load->model('Grupo_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    }
    
    /* *****Funcion que verifica el acceso al sistema**** */
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Listing of grupo
     */
    function index()
    {
        $this->load->model('Carrera_model');
        $data['all_carrera'] = $this->Carrera_model->get_all_carreras();
        
        $this->load->model('Paralelo_model');
        $data['all_paralelo'] = $this->Paralelo_model->get_all_paralelo();
        
        $this->load->model('Docente_model');
        $data['all_docente'] = $this->Docente_model->get_all_docente_activo();
        
        $this->load->model('Aula_model');
        $data['all_aula'] = $this->Aula_model->get_all_aula();
        
        $this->load->model('Periodo_model');
        $data['all_periodo'] = $this->Periodo_model->get_all_periodo();
        
        $this->load->model('Dia_model');
        $data['all_dia'] = $this->Dia_model->get_all_dias_activos();
        
        //$data['grupo'] = $this->Grupo_model->get_all_grupo();
        
        $data['_view'] = 'grupo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new grupo
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'horario_id' => $this->input->post('horario_id'),
				'docente_id' => $this->input->post('docente_id'),
				'gestion_id' => $this->input->post('gestion_id'),
				'usuario_id' => $this->input->post('usuario_id'),
				'aula_id' => $this->input->post('aula_id'),
				'materia_id' => $this->input->post('materia_id'),
				'grupo_nombre' => $this->input->post('grupo_nombre'),
				'grupo_descripcion' => $this->input->post('grupo_descripcion'),
				'grupo_horanicio' => $this->input->post('grupo_horanicio'),
				'grupo_horafin' => $this->input->post('grupo_horafin'),
            );
            
            $grupo_id = $this->Grupo_model->add_grupo($params);
            redirect('grupo/index');
        }
        else
        {
			$this->load->model('Horario_model');
			$data['all_horario'] = $this->Horario_model->get_all_horario();

			$this->load->model('Docente_model');
			$data['all_docente'] = $this->Docente_model->get_all_docente();

			$this->load->model('Gestion_model');
			$data['all_gestion'] = $this->Gestion_model->get_all_gestion();

			$this->load->model('Usuario_model');
			$data['all_usuario'] = $this->Usuario_model->get_all_usuario();

			$this->load->model('Aula_model');
			$data['all_aula'] = $this->Aula_model->get_all_aula();

			$this->load->model('Materia_model');
			$data['all_materia'] = $this->Materia_model->get_all_materia();
            
            $data['_view'] = 'grupo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a grupo
     */
    function edit($grupo_id)
    {   
        // check if the grupo exists before trying to edit it
        $data['grupo'] = $this->Grupo_model->get_grupo($grupo_id);
        
        if(isset($data['grupo']['grupo_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'horario_id' => $this->input->post('horario_id'),
					'docente_id' => $this->input->post('docente_id'),
					'gestion_id' => $this->input->post('gestion_id'),
					'usuario_id' => $this->input->post('usuario_id'),
					'aula_id' => $this->input->post('aula_id'),
					'materia_id' => $this->input->post('materia_id'),
					'grupo_nombre' => $this->input->post('grupo_nombre'),
					'grupo_descripcion' => $this->input->post('grupo_descripcion'),
					'grupo_horanicio' => $this->input->post('grupo_horanicio'),
					'grupo_horafin' => $this->input->post('grupo_horafin'),
                );

                $this->Grupo_model->update_grupo($grupo_id,$params);            
                redirect('grupo/index');
            }
            else
            {
				$this->load->model('Horario_model');
				$data['all_horario'] = $this->Horario_model->get_all_horario();

				$this->load->model('Docente_model');
				$data['all_docente'] = $this->Docente_model->get_all_docente();

				$this->load->model('Gestion_model');
				$data['all_gestion'] = $this->Gestion_model->get_all_gestion();

				$this->load->model('Usuario_model');
				$data['all_usuario'] = $this->Usuario_model->get_all_usuario();

				$this->load->model('Aula_model');
				$data['all_aula'] = $this->Aula_model->get_all_aula();

				$this->load->model('Materia_model');
				$data['all_materia'] = $this->Materia_model->get_all_materia();

                $data['_view'] = 'grupo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The grupo you are trying to edit does not exist.');
    } 

    /*
     * Deleting grupo
     */
    function remove($grupo_id)
    {
        $grupo = $this->Grupo_model->get_grupo($grupo_id);

        // check if the grupo exists before trying to delete it
        if(isset($grupo['grupo_id']))
        {
            $this->Grupo_model->delete_grupo($grupo_id);
            redirect('grupo/index');
        }
        else
            show_error('The grupo you are trying to delete does not exist.');
    }
    
    /****obtener planes academicos de una carrera****/
    function get_planes_academicos()
    {
        if ($this->input->is_ajax_request())
        {
            $this->load->model('Plan_academico_model');
            $carrera_id = $this->input->post('carrera_id');
            if ($carrera_id!=""){
                $datos = $this->Plan_academico_model->get_plan_acad_carr($carrera_id);
                echo json_encode($datos);
            }
            else echo json_encode(null);
        }
        else
        {
            show_404();
        }
        
    }
    
    /****obtener planes academicos de una carrera****/
    function get_docente()
    {
        if ($this->input->is_ajax_request())
        {
            $this->load->model('Docente_model');
            $docente_id = $this->input->post('docente_id');
            if ($docente_id!=""){
                $datos = $this->Docente_model->get_docente($docente_id);
                echo json_encode($datos);
            }
            else echo json_encode(null);
        }
        else
        {
            show_404();
        }
        
    }
    /****obtener Niveles de un plan academico****/
    function get_niveles()
    {
        if ($this->input->is_ajax_request())
        {
            $this->load->model('Nivel_model');
            $planacad_id = $this->input->post('planacad_id');
            if ($planacad_id != ""){
                $datos = $this->Nivel_model->get_all_nivel_forplan($planacad_id);
                echo json_encode($datos);
            }
            else echo json_encode(null);
        }
        else
        {
            show_404();
        }
        
    }
    /****obtener Materias de un Nivel ****/
    function get_materias()
    {
        if ($this->input->is_ajax_request())
        {
            $this->load->model('Materia_model');
            $nivel_id = $this->input->post('nivel_id');
            if ($nivel_id != ""){
                $datos = $this->Materia_model->get_all_materia_nivel($nivel_id);
                echo json_encode($datos);
            }
            else echo json_encode(null);
        }
        else
        {
            show_404();
        }
        
    }
    /****obtener grupos de DOCENTE ****/
    function get_grupodocente()
    {
        if ($this->input->is_ajax_request())
        {
            $docente_id = $this->input->post('docente_id');
            if ($docente_id != ""){
                $datos = $this->Grupo_model->get_allgrupo_docente($docente_id);
                echo json_encode($datos);
            }
            else echo json_encode(null);
        }
        else
        {
            show_404();
        }
        
    }
    
    /**** Registrar nuevo grupo docente ****/
    function registrar_newgrupodocente()
    {
        if ($this->input->is_ajax_request())
        {
            $carrera_id   = $this->input->post('carrera_id');
            $planacad_id  = $this->input->post('planacad_id');
            $nivel_id     = $this->input->post('nivel_id');
            $docente_id   = $this->input->post('docente_id');
            $materia_id   = $this->input->post('materia_id');
            $grupo_nombre = $this->input->post('grupo_nombre');
            /*$dia1 = $this->input->post('dia1');
            $dia2 = $this->input->post('dia2');
            $dia3 = $this->input->post('dia3');
            $dia4 = $this->input->post('dia4');
            $dia5 = $this->input->post('dia5');
            $dia6 = $this->input->post('dia6');
            $dia7 = $this->input->post('dia7');
            $periodo1 = $this->input->post('periodo1');
            $periodo2 = $this->input->post('periodo2');
            $periodo3 = $this->input->post('periodo3');
            $periodo4 = $this->input->post('periodo4');
            $periodo5 = $this->input->post('periodo5');
            $periodo6 = $this->input->post('periodo6');
            $periodo7 = $this->input->post('periodo7');
            $aula1 = $this->input->post('aula1');
            $aula2 = $this->input->post('aula2');
            $aula3 = $this->input->post('aula3');
            $aula4 = $this->input->post('aula4');
            $aula5 = $this->input->post('aula5');
            $aula6 = $this->input->post('aula6');
            $aula7 = $this->input->post('aula7');*/
            $this->load->model('Horario_model');
            
            $gestion_id = $this->session_data['gestion_id'];
            $usuario_id = $this->session_data['usuario_id'];
            
            $estado_id = 1;
            $yaregistrado = false;
            for ($index = 1; $index < 8; $index++) {
                $aula    = $this->input->post('aula'.$index);
                $periodo = $this->input->post('periodo'.$index);
                $dia     = $this->input->post('dia'.$index);
                if(!empty($aula) && !empty($periodo) && !empty($dia)){
                    $hayregistrado = $this->Horario_model->existe_horario($aula, $periodo, $dia);
                    if($hayregistrado['res'] >0){
                        $yaregistrado = true;
                    }
                }
            }
            if($yaregistrado == false){
                for ($i = 1; $i < 8; $i++) {
                    if($this->input->post('dia'.$i) != ""){
                        $params = array(
                            'estado_id'  => $estado_id,
                            'periodo_id' => $this->input->post('periodo'.$i),
                            'dia_id'     => $this->input->post('dia'.$i),
                            'aula_id'    => $this->input->post('aula'.$i),
                        );
                        $horario_id = $this->Horario_model->add_horario($params);
                        $paramsg = array(
                            'horario_id' => $horario_id,
                            'docente_id' => $docente_id,
                            'gestion_id' => $gestion_id,
                            'usuario_id' => $usuario_id,
                            'aula_id' => $this->input->post('aula'.$i),
                            'materia_id' => $materia_id,
                            'grupo_nombre' => $grupo_nombre,
                        );
                        $grupo_id = $this->Grupo_model->add_grupo($paramsg);
                    }
                }
            /*if($dia1 != ""){
                $params = array(
                    'estado_id'  => $estado_id,
                    'periodo_id' => $periodo1,
                    'dia_id'     => $dia1,
                    'aula_id'    => $aula1,
                );
                $horario_id = $this->Horario_model->add_horario($params);
                $paramsg = array(
                    'horario_id' => $horario_id,
                    'docente_id' => $docente_id,
                    'gestion_id' => $gestion_id,
                    'usuario_id' => $usuario_id,
                    'aula_id' => $aula1,
                    'materia_id' => $materia_id,
                    'grupo_nombre' => $grupo_nombre,
                );
                $grupo_id = $this->Grupo_model->add_grupo($paramsg);
            }*/
                echo json_encode("ok");
            }else{
                echo json_encode(null);
            }
            
        }
        else
        {
            show_404();
        }
        
    }
}
