<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Institucion extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Institucion_model');
    } 

    /*
     * Listing of institucion
     */
    function index()
    {
        $data['institucion'] = $this->Institucion_model->get_all_institucion();
        
        $data['_view'] = 'institucion/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new institucion
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('institucion_nombre','Institucion Nombre','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'institucion_nombre' => $this->input->post('institucion_nombre'),
				'institucion_direccion' => $this->input->post('institucion_direccion'),
				'institucion_telefono' => $this->input->post('institucion_telefono'),
				'institucion_fechacreacion' => $this->input->post('institucion_fechacreacion'),
				'institucion_logo' => $this->input->post('institucion_logo'),
				'institucion_ubicacion' => $this->input->post('institucion_ubicacion'),
				'institucion_distrito' => $this->input->post('institucion_distrito'),
				'institucion_zona' => $this->input->post('institucion_zona'),
				'institucion_slogan' => $this->input->post('institucion_slogan'),
				'institucion_departamento' => $this->input->post('institucion_departamento'),
				'institucion_codigo' => $this->input->post('institucion_codigo'),
            );
            
            $institucion_id = $this->Institucion_model->add_institucion($params);
            redirect('institucion/index');
        }
        else
        {            
            $data['_view'] = 'institucion/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a institucion
     */
    function edit($institucion_id)
    {   
        // check if the institucion exists before trying to edit it
        $data['institucion'] = $this->Institucion_model->get_institucion($institucion_id);
        
        if(isset($data['institucion']['institucion_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('institucion_nombre','Institucion Nombre','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'institucion_nombre' => $this->input->post('institucion_nombre'),
					'institucion_direccion' => $this->input->post('institucion_direccion'),
					'institucion_telefono' => $this->input->post('institucion_telefono'),
					'institucion_fechacreacion' => $this->input->post('institucion_fechacreacion'),
					'institucion_logo' => $this->input->post('institucion_logo'),
					'institucion_ubicacion' => $this->input->post('institucion_ubicacion'),
					'institucion_distrito' => $this->input->post('institucion_distrito'),
					'institucion_zona' => $this->input->post('institucion_zona'),
					'institucion_slogan' => $this->input->post('institucion_slogan'),
					'institucion_departamento' => $this->input->post('institucion_departamento'),
					'institucion_codigo' => $this->input->post('institucion_codigo'),
                );

                $this->Institucion_model->update_institucion($institucion_id,$params);            
                redirect('institucion/index');
            }
            else
            {
                $data['_view'] = 'institucion/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The institucion you are trying to edit does not exist.');
    } 

    /*
     * Deleting institucion
     */
    function remove($institucion_id)
    {
        $institucion = $this->Institucion_model->get_institucion($institucion_id);

        // check if the institucion exists before trying to delete it
        if(isset($institucion['institucion_id']))
        {
            $this->Institucion_model->delete_institucion($institucion_id);
            redirect('institucion/index');
        }
        else
            show_error('The institucion you are trying to delete does not exist.');
    }
    
}
