<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Material extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Material_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    }

    /* *****Funcion que verifica el acceso al sistema**** */
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * lista material
     */
    function index($materia_id)
    {
        // if($this->acceso(65)){
            $docente_id = $this->session_data['usuario_id'];
            // $data['materia'] = $this->Materia_model->get_all_materia();
            $data['material'] = $this->Material_model->get_all_material($docente_id,$materia_id);
            $data['materia'] = $materia_id;
            $data['_view'] = 'material/index';
            $this->load->view('layouts/main',$data);
        // }
    }

    /*
    * Añadir nuevo material
    */
    function add($materia_id){
        // if($this->acceso(66)){
            $docente_id = $this->session_data['usuario_id'];
            if(isset($_POST) && count($_POST) > 0){   
                $params = array(
                    'material_titulo' => $this->input->post('material_titulo'),
                    'material_descripcion' => $this->input->post('material_descripcion'),
                    'material_enlace' => $this->input->post('material_enlace'),
                    'material_tipo' => $this->input->post('material_tipo'),
                    'material_recomendacion' => $this->input->post('material_recomendacion'),
                    'materia_id'=> $materia_id,
                    'estado_id' => $this->input->post('estado_id'),
                    'docente_id' => $docente_id,
                    'material_fecha' => date('Y-m-d H:i:s'),
                );
                $material_id = $this->Material_model->add_material($params);
                redirect('material/index/'.$materia_id);
            }else{
                $data['estados'] = $this->Material_model->get_estado();
                $data['materia'] = $materia_id;
                $data['_view'] = 'material/add';
                $this->load->view('layouts/main',$data);
            }
        // }
    }

    /* 
    * Editar un material
    */
    function edit($materialest_id){
        // if($this->acceso(67)){
            // check if the material exists before trying to edit it
            $data['material'] = $this->Material_model->get_material($materialest_id);

            if(isset($data['material']['materialest_id']))
            {
                if(isset($_POST) && count($_POST) > 0)     
                {   
                    $params = array(
                        'material_titulo' => $this->input->post('material_titulo'),
                        'material_descripcion' => $this->input->post('material_descripcion'),
                        'material_enlace' => $this->input->post('material_enlace'),
                        'material_tipo' => $this->input->post('material_tipo'),
                        'material_recomendacion' => $this->input->post('material_recomendacion'),
                        'materia_id'=> $data['material']['materia_id'],
                        'estado_id' => $this->input->post('estado_id'),
                        'docente_id' => $data['material']['docente_id'],
                        'material_fecha' => date('Y-m-d H:i:s'),
                    );

                    $this->Material_model->update_material($materialest_id,$params);            
                    redirect('material/index/'.$data['material']['materia_id']);
                }else{
                    $data['estados'] = $this->Material_model->get_estado();
            
                    $data['_view'] = 'material/edit';
                    $this->load->view('layouts/main',$data);
                }
            }else
                show_error('The material you are trying to edit does not exist.');
        // }
    }
}