<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Nivel extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Nivel_model');
    } 

    /*
     * Listing of nivel
     */
    function index()
    {
        $data['nivel'] = $this->Nivel_model->get_all_nivel();
        
        $data['_view'] = 'nivel/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new nivel
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'plan_academico_id' => $this->input->post('plan_academico_id'),
				'nivel_descripcion' => $this->input->post('nivel_descripcion'),
            );
            
            $nivel_id = $this->Nivel_model->add_nivel($params);
            redirect('nivel/index');
        }
        else
        {
			$this->load->model('Plan_academico_model');
			$data['all_plan_academico'] = $this->Plan_academico_model->get_all_plan_academico();
            
            $data['_view'] = 'nivel/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a nivel
     */
    function edit($nivel_id)
    {   
        // check if the nivel exists before trying to edit it
        $data['nivel'] = $this->Nivel_model->get_nivel($nivel_id);
        
        if(isset($data['nivel']['nivel_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'plan_academico_id' => $this->input->post('plan_academico_id'),
					'nivel_descripcion' => $this->input->post('nivel_descripcion'),
                );

                $this->Nivel_model->update_nivel($nivel_id,$params);            
                redirect('nivel/index');
            }
            else
            {
				$this->load->model('Plan_academico_model');
				$data['all_plan_academico'] = $this->Plan_academico_model->get_all_plan_academico();

                $data['_view'] = 'nivel/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The nivel you are trying to edit does not exist.');
    } 

    /*
     * Deleting nivel
     */
    function remove($nivel_id)
    {
        $nivel = $this->Nivel_model->get_nivel($nivel_id);

        // check if the nivel exists before trying to delete it
        if(isset($nivel['nivel_id']))
        {
            $this->Nivel_model->delete_nivel($nivel_id);
            redirect('nivel/index');
        }
        else
            show_error('The nivel you are trying to delete does not exist.');
    }
    
}
