<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Periodo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Periodo_model');
    } 

    /*
     * Listing of periodo
     */
    function index()
    {
        $data['periodo'] = $this->Periodo_model->get_all_periodo();
        
        $data['_view'] = 'periodo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new periodo
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('periodo_nombre','Periodo Nombre','required');
		$this->form_validation->set_rules('periodo_horainicio','Periodo Horainicio','required');
		$this->form_validation->set_rules('periodo_horafin','Periodo Horafin','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'periodo_nombre' => $this->input->post('periodo_nombre'),
				'periodo_horainicio' => $this->input->post('periodo_horainicio'),
				'periodo_horafin' => $this->input->post('periodo_horafin'),
            );
            
            $periodo_id = $this->Periodo_model->add_periodo($params);
            redirect('periodo/index');
        }
        else
        {            
            $data['_view'] = 'periodo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a periodo
     */
    function edit($periodo_id)
    {   
        // check if the periodo exists before trying to edit it
        $data['periodo'] = $this->Periodo_model->get_periodo($periodo_id);
        
        if(isset($data['periodo']['periodo_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('periodo_nombre','Periodo Nombre','required');
			$this->form_validation->set_rules('periodo_horainicio','Periodo Horainicio','required');
			$this->form_validation->set_rules('periodo_horafin','Periodo Horafin','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'periodo_nombre' => $this->input->post('periodo_nombre'),
					'periodo_horainicio' => $this->input->post('periodo_horainicio'),
					'periodo_horafin' => $this->input->post('periodo_horafin'),
                );

                $this->Periodo_model->update_periodo($periodo_id,$params);            
                redirect('periodo/index');
            }
            else
            {
                $data['_view'] = 'periodo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The periodo you are trying to edit does not exist.');
    } 

    /*
     * Deleting periodo
     */
    function remove($periodo_id)
    {
        $periodo = $this->Periodo_model->get_periodo($periodo_id);

        // check if the periodo exists before trying to delete it
        if(isset($periodo['periodo_id']))
        {
            $this->Periodo_model->delete_periodo($periodo_id);
            redirect('periodo/index');
        }
        else
            show_error('The periodo you are trying to delete does not exist.');
    }
    
}
