<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_aula extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tipo_aula_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    }
    /* *****Funcion que verifica el acceso al sistema**** */
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Listing of tipo_aula
     */
    function index()
    {
        if($this->acceso(112)){
            $data['tipo_aula'] = $this->Tipo_aula_model->get_all_tipo_aula();

            $data['_view'] = 'tipo_aula/index';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Adding a new tipo_aula
     */
    function add()
    {
        if($this->acceso(113)){
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                                    'tipoaula_descripcion' => $this->input->post('tipoaula_descripcion'),
                );

                $tipo_aula_id = $this->Tipo_aula_model->add_tipo_aula($params);
                redirect('tipo_aula/index');
            }
            else
            {            
                $data['_view'] = 'tipo_aula/add';
                $this->load->view('layouts/main',$data);
            }
        }
    }  

    /*
     * Editing a tipo_aula
     */
    function edit($tipoaula_id)
    {
        if($this->acceso(114)){
            // check if the tipo_aula exists before trying to edit it
            $data['tipo_aula'] = $this->Tipo_aula_model->get_tipo_aula($tipoaula_id);

            if(isset($data['tipo_aula']['tipoaula_id']))
            {
                if(isset($_POST) && count($_POST) > 0)     
                {   
                    $params = array(
                                            'tipoaula_descripcion' => $this->input->post('tipoaula_descripcion'),
                    );

                    $this->Tipo_aula_model->update_tipo_aula($tipoaula_id,$params);            
                    redirect('tipo_aula/index');
                }
                else
                {
                    $data['_view'] = 'tipo_aula/edit';
                    $this->load->view('layouts/main',$data);
                }
            }
            else
                show_error('The tipo_aula you are trying to edit does not exist.');
        }
    } 

    /*
     * Deleting tipo_aula
     */
    function remove($tipoaula_id)
    {
        if($this->acceso(112)){
            $tipo_aula = $this->Tipo_aula_model->get_tipo_aula($tipoaula_id);

            // check if the tipo_aula exists before trying to delete it
            if(isset($tipo_aula['tipoaula_id']))
            {
                $this->Tipo_aula_model->delete_tipo_aula($tipoaula_id);
                redirect('tipo_aula/index');
            }
            else
                show_error('The tipo_aula you are trying to delete does not exist.');
        }
    }
    
}
