<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Area_carrera_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get area_carrera by areacarrera_id
     */
    function get_area_carrera($areacarrera_id)
    {
        $area_carrera = $this->db->query("
            SELECT
                *

            FROM
                `area_carrera`

            WHERE
                `areacarrera_id` = ?
        ",array($areacarrera_id))->row_array();

        return $area_carrera;
    }
        
    /*
     * Get all area_carrera
     */
    function get_all_area_carrera()
    {
        $area_carrera = $this->db->query("
            SELECT
                *

            FROM
                `area_carrera`

            WHERE
                1 = 1

            ORDER BY `areacarrera_id` DESC
        ")->result_array();

        return $area_carrera;
    }
        
    /*
     * function to add new area_carrera
     */
    function add_area_carrera($params)
    {
        $this->db->insert('area_carrera',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update area_carrera
     */
    function update_area_carrera($areacarrera_id,$params)
    {
        $this->db->where('areacarrera_id',$areacarrera_id);
        return $this->db->update('area_carrera',$params);
    }
    
    /*
     * function to delete area_carrera
     */
    function delete_area_carrera($areacarrera_id)
    {
        return $this->db->delete('area_carrera',array('areacarrera_id'=>$areacarrera_id));
    }
}
