<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Area_materium_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get area_materium by area_id
     */
    function get_area_materium($area_id)
    {
        $area_materium = $this->db->query("
            SELECT
                *

            FROM
                `area_materia`

            WHERE
                `area_id` = ?
        ",array($area_id))->row_array();

        return $area_materium;
    }
        
    /*
     * Get all area_materia
     */
    function get_all_area_materia()
    {
        $area_materia = $this->db->query("
            SELECT
                *

            FROM
                `area_materia`

            WHERE
                1 = 1

            ORDER BY `area_id` DESC
        ")->result_array();

        return $area_materia;
    }
        
    /*
     * function to add new area_materium
     */
    function add_area_materium($params)
    {
        $this->db->insert('area_materia',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update area_materium
     */
    function update_area_materium($area_id,$params)
    {
        $this->db->where('area_id',$area_id);
        return $this->db->update('area_materia',$params);
    }
    
    /*
     * function to delete area_materium
     */
    function delete_area_materium($area_id)
    {
        return $this->db->delete('area_materia',array('area_id'=>$area_id));
    }
}
