<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Citacion_model extends CI_Model{
    
    function __construct()
    {
        parent::__construct();
    }
    /*
    * Obtener todas las citaciones de un docente 
    */
    function get_citaciones($docente_id){
        $citaciones = $this->db->query(
            "SELECT c.*, e.`estudiante_nombre`,e.`estudiante_apellidos`, es.`estado_descripcion`
            FROM citacion as c 
            LEFT JOIN estudiante as e on c.`estudiante_id` = e.estudiante_id
            LEFT JOIN estado as es on c.`estado_id` = es.`estado_id`
            WHERE c.`docente_id` = $docente_id
        ")->result_array();
        return $citaciones;
    }

    /*
    * Estados de citacion 
    */
    function get_estado(){
        $estados = $this->db->query(
            "SELECT * 
            FROM estado
            WHERE estado_tipo = 1
            ")->result_array();
        return $estados;
    }

    /*
    * Obtener citacion 
    */
    function get_citacion($citacion_id){
        $citacion = $this->db->query(
            "SELECT *
            FROM citacion
            where citacion_id = $citacion_id"
        )->row_array();
        return $citacion;
    }

    /*
    * Agregar citacion 
    */
    function add_citacion($params){
        $this->db->insert('citacion',$params);
        return $this->db->insert_id();
    }

    /*
    * Actualizar citacion 
    */
    function update_citacion($citacion_id, $params){
        $this->db->where('citacion_id',$citacion_id);
        return $this->db->update('citacion',$params);
    }

    /*
    *   Cantidad total de citaciones de estudiante 
    */
    function get_citaciones_estudiante($estudiante_id){
        $total =$this->db->query(
            "select if(COUNT(c.`citacion_id`)>0,COUNT(c.`citacion_id`),0) as total_citaciones
            from citacion as c 
            where c.`estado_id` = 1
            and c.`estudiante_id` = $estudiante_id"
        )->row_array();
    }
}