<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dia_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get dia by dia_id
     */
    function get_dia($dia_id)
    {
        return $this->db->get_where('dia',array('dia_id'=>$dia_id))->row_array();
    }
        
    /*
     * Get all dia
     */
    function get_all_dia()
    {
        $this->db->select('d.*, e.estado_descripcion, e.estado_color');
        $this->db->from('dia d');
        $this->db->join('estado e', 'd.estado_id = e.estado_id');
        return $this->db->get()->result_array();
    }
        
    /*
     * function to add new dia
     */
    function add_dia($params)
    {
        $this->db->insert('dia',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update dia
     */
    function update_dia($dia_id,$params)
    {
        $this->db->where('dia_id',$dia_id);
        return $this->db->update('dia',$params);
    }
    
    /*
     * function to delete dia
     */
    function delete_dia($dia_id)
    {
        return $this->db->delete('dia',array('dia_id'=>$dia_id));
    }
    
    /*
     * Get all dia
     */
    function get_all_dias_activos()
    {
        $this->db->select('d.*');
        $this->db->from('dia d');
        $this->db->where('estado_id', 1);
        return $this->db->get()->result_array();
    }
}
