<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Docente_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get docente by docente_id
     */
    function get_docente($docente_id)
    {
        $docente = $this->db->query("
            SELECT
                *

            FROM
                `docente`

            WHERE
                `docente_id` = ?
        ",array($docente_id))->row_array();

        return $docente;
    }
    
    /*
     * Get all docente count
     */
    function get_all_docente_count()
    {
        $docente = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `docente`
        ")->row_array();

        return $docente['count'];
    }
        
    /*
     * Get all docente
     */
    function get_all_docente($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $docente = $this->db->query("
            SELECT
                d.*, e.*, g.*, ec.*

            FROM
                docente d, estado e, genero g, estado_civil ec

            WHERE
                d.estado_id=e.estado_id
                and d.genero_id=g.genero_id
                and d.estadocivil_id=ec.estadocivil_id

            ORDER BY `docente_id` DESC

            " . $limit_condition . "
        ")->result_array();

        return $docente;
    }
        
    /*
     * function to add new docente
     */
    function add_docente($params)
    {
        $this->db->insert('docente',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update docente
     */
    function update_docente($docente_id,$params)
    {
        $this->db->where('docente_id',$docente_id);
        return $this->db->update('docente',$params);
    }
    
    /*
     * function to delete docente
     */
    function delete_docente($docente_id)
    {
        return $this->db->delete('docente',array('docente_id'=>$docente_id));
    }
}
