<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Estudiante_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estudiante by estudiante_id
     */
    function get_estudiante($estudiante_id)
    {
        $estudiante = $this->db->query("
            SELECT
                *

            FROM
                `estudiante`

            WHERE
                `estudiante_id` = ?
        ",array($estudiante_id))->row_array();

        return $estudiante;
    }
    
    /*
     * Get all estudiante count
     */
    function get_all_estudiante_count()
    {
        $estudiante = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `estudiante`
        ")->row_array();

        return $estudiante['count'];
    }
        
    /*
     * Get all estudiante
     */
    function get_all_estudiante($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $estudiante = $this->db->query("
            SELECT
                es.*, e.*, ec.*, g.*

            FROM
                estudiante es, estado e, estado_civil ec, genero g

            WHERE
                es.estado_id=e.estado_id
                and es.genero_id=g.genero_id
                and es.estadocivil_id=ec.estadocivil_id

            ORDER BY `estudiante_id` DESC

            " . $limit_condition . "
        ")->result_array();

        return $estudiante;
    }
    function get_estudiantes($parametro)
    {
        $estudiante = $this->db->query("
            SELECT
                es.*, e.*, ec.*, g.*

            FROM
                estudiante es, estado e, estado_civil ec, genero g

            WHERE
                es.estado_id=e.estado_id
                and es.genero_id=g.genero_id
                and es.estadocivil_id=ec.estadocivil_id
                and es.estudiante_nombre like '%".$parametro."%' 
                or es.estudiante_apellidos like '%".$parametro."%' 

            ORDER BY `estudiante_id` DESC

        ")->result_array();

        return $estudiante;
    }
        
    /*
     * Get all estudiante
     */
    function get_estudiante_por_id($estudiante_id)
    {
        $sql = "select * from estudiante where estudiante_id = ".$estudiante_id;
        
        $estudiante = $this->db->query($sql)->result_array();
        return $estudiante;
    }
        
    /*
     * Get datos estudiante temporal
     */
    function get_estudiante_temporal()
    {
        $sql = "select 0 as estudiante_id,
                'NO DEFINIDIO' as estadocivil_id,
                'NO DEFINIDIO' as estudiante_nombre,
                'NO DEFINIDIO' as estudiante_apellidos,
                'NO DEFINIDIO' as estudiante_fechanac,
                0 as estudiante_edad,
                'NO DEFINIDIO' as estudiante_ci,
                'NO DEFINIDIO' as estudiante_extci,
                'NO DEFINIDIO' as estudiante_codigo,
                'NO DEFINIDIO' as estudiante_direccion,
                'NO DEFINIDIO' as estudiante_telefono,
                'NO DEFINIDIO' as estudiante_celular,
                'NO DEFINIDIO' as estudiante_foto,
                'NO DEFINIDIO' as estudiante_lugarnac,
                'NO DEFINIDIO' as estudiante_nacionalidad,
                'NO DEFINIDIO' as estudiante_establecimiento,
                'NO DEFINIDIO' as estudiante_distrito,
                'NO DEFINIDIO' as estudiante_apoderado,
                0 as estudiante_nit,
                'SIN NOMBRE' as estudiante_razon
                ";
        $estudiante = $this->db->query($sql)->result_array();
        return $estudiante;
    }
        
    /*
     * function to add new estudiante
     */
    function add_estudiante($params)
    {
        $this->db->insert('estudiante',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update estudiante
     */
    function update_estudiante($estudiante_id,$params)
    {
        $this->db->where('estudiante_id',$estudiante_id);
        return $this->db->update('estudiante',$params);
    }
    
    /*
     * function to delete estudiante
     */
    function delete_estudiante($estudiante_id)
    {
        return $this->db->delete('estudiante',array('estudiante_id'=>$estudiante_id));
    }
    function get_esteestudiante($estudiante_id)
    {
        $estudiante = $this->db->query("
            SELECT
                e.*, g.genero_nombre, ec.estadocivil_descripcion 

            FROM
                estudiante e
            LEFT JOIN genero g on e.genero_id = g.genero_id
            LEFT JOIN estado_civil ec on e.estadocivil_id = ec.estadocivil_id

            WHERE
                e.estudiante_id = $estudiante_id ")->row_array();

        return $estudiante;
    }
    function get_kardexcarrera_estudiante($carrera_id, $estudiante_id)
    {
        $mikardex = $this->db->query("
            SELECT
                ka.*, m.materia_nombre, m.materia_id

            FROM
                estudiante e
            LEFT JOIN inscripcion i on e.estudiante_id = i.estudiante_id
            LEFT JOIN carrera c on i.carrera_id = c.carrera_id
            LEFT JOIN kardex_academico ka on i.inscripcion_id = ka.inscripcion_id
            LEFT JOIN materia_asignada ma on ka.kardexacad_id = ma.kardexacad_id
            LEFT JOIN materia m on ma.materia_id = m.materia_id
            WHERE
                e.estudiante_id = $estudiante_id
                 and c.carrera_id = $carrera_id ")->result_array();

        return $mikardex;
    }
    function get_kardexcarrera_estudianteborrar($carrera_id, $estudiante_id)
    {
        $mikardex = $this->db->query("
            SELECT
                m.materia_id, m.materia_nombre, m.materia_codigo, m.materia_horas,
                c.carrera_modalidad,
                pr.mat_materia_id, pr.materia_codigo as cod
            FROM
                materia m
            LEFT JOIN materia pr on m.materia_id = pr.materia_id
            LEFT JOIN nivel n on m.nivel_id = n.nivel_id
            LEFT JOIN plan_academico pa on n.planacad_id = pa.planacad_id
            LEFT JOIN carrera c on pa.carrera_id = c.carrera_id
            where
                 c.carrera_id = $carrera_id
            
            GROUP BY m.materia_id ")->result_array();

        return $mikardex;
    }
    function get_estudiante_kardexecon($estudiante_id)
    {
        $kardex_economico = $this->db->query("
            SELECT
                i.*, ke.*, c.*, e.*

            FROM
                inscripcion i

            LEFT JOIN kardex_economico ke ON i.inscripcion_id=ke.inscripcion_id
            LEFT JOIN carrera c ON i.carrera_id=c.carrera_id
            LEFT JOIN estudiante e ON i.estudiante_id=e.estudiante_id

            WHERE
                e.estudiante_id = $estudiante_id

            ORDER BY `kardexeco_id` DESC
        ")->result_array();

        return $kardex_economico;
    }
}
