<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Estudiante_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estudiante by estudiante_id
     */
    function get_estudiante($estudiante_id)
    {
        $estudiante = $this->db->query("
            SELECT
                *

            FROM
                `estudiante`

            WHERE
                `estudiante_id` = ?
        ",array($estudiante_id))->row_array();

        return $estudiante;
    }
    
    /*
     * Get all estudiante count
     */
    function get_all_estudiante_count()
    {
        $estudiante = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `estudiante`
        ")->row_array();

        return $estudiante['count'];
    }
        
    /*
     * Get all estudiante
     */
    function get_all_estudiante($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $estudiante = $this->db->query("
            SELECT
                es.*, e.*, ec.*, g.*

            FROM
                estudiante es, estado e, estado_civil ec, genero g

            WHERE
                es.estado_id=e.estado_id
                and es.genero_id=g.genero_id
                and es.estadocivil_id=ec.estadocivil_id

            ORDER BY `estudiante_id` DESC

            " . $limit_condition . "
        ")->result_array();

        return $estudiante;
    }
    function get_estudiantes($parametro)
    {
        $estudiante = $this->db->query("
            SELECT
                es.*, e.*, ec.*, g.*

            FROM
                estudiante es, estado e, estado_civil ec, genero g

            WHERE
                es.estado_id=e.estado_id
                and es.genero_id=g.genero_id
                and es.estadocivil_id=ec.estadocivil_id
                and es.estudiante_nombre like '%".$parametro."%' 
                or es.estudiante_apellidos like '%".$parametro."%' 

            ORDER BY `estudiante_id` DESC

        ")->result_array();

        return $estudiante;
    }
        
    /*
     * Get all estudiante
     */
    function get_estudiante_por_id($estudiante_id)
    {
        $sql = "select * from estudiante where estudiante_id = ".$estudiante_id;
        
        $estudiante = $this->db->query($sql)->result_array();
        return $estudiante;
    }
        
    /*
     * Get datos estudiante temporal
     */
    function get_estudiante_temporal()
    {
        $sql = "select 0 as estudiante_id,
                'NO DEFINIDIO' as estadocivil_id,
                'NO DEFINIDIO' as estudiante_nombre,
                'NO DEFINIDIO' as estudiante_apellidos,
                'NO DEFINIDIO' as estudiante_fechanac,
                0 as estudiante_edad,
                'NO DEFINIDIO' as estudiante_ci,
                'NO DEFINIDIO' as estudiante_extci,
                'NO DEFINIDIO' as estudiante_codigo,
                'NO DEFINIDIO' as estudiante_direccion,
                'NO DEFINIDIO' as estudiante_telefono,
                'NO DEFINIDIO' as estudiante_celular,
                'NO DEFINIDIO' as estudiante_foto,
                'NO DEFINIDIO' as estudiante_lugarnac,
                'NO DEFINIDIO' as estudiante_nacionalidad,
                'NO DEFINIDIO' as estudiante_establecimiento,
                'NO DEFINIDIO' as estudiante_distrito,
                'NO DEFINIDIO' as estudiante_apoderado,
                0 as estudiante_nit,
                'SIN NOMBRE' as estudiante_razon
                ";
        $estudiante = $this->db->query($sql)->result_array();
        return $estudiante;
    }
        
    /*
     * function to add new estudiante
     */
    function add_estudiante($params)
    {
        $this->db->insert('estudiante',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update estudiante
     */
    function update_estudiante($estudiante_id,$params)
    {
        $this->db->where('estudiante_id',$estudiante_id);
        return $this->db->update('estudiante',$params);
    }
    
    /*
     * function to delete estudiante
     */
    function delete_estudiante($estudiante_id)
    {
        return $this->db->delete('estudiante',array('estudiante_id'=>$estudiante_id));
    }
}
