<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Estudiante_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estudiante by estudiante_id
     */
    function get_estudiante($estudiante_id)
    {
        $estudiante = $this->db->query("
            SELECT
                *

            FROM
                `estudiante`

            WHERE
                `estudiante_id` = ?
        ",array($estudiante_id))->row_array();

        return $estudiante;
    }
    
    /*
     * Get all estudiante count
     */
    function get_all_estudiante_count()
    {
        $estudiante = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `estudiante`
        ")->row_array();

        return $estudiante['count'];
    }
        
    /*
     * Get all estudiante
     */
    function get_all_estudiante($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $estudiante = $this->db->query("
            SELECT
                *

            FROM
                `estudiante`

            WHERE
                1 = 1

            ORDER BY `estudiante_id` DESC

            " . $limit_condition . "
        ")->result_array();

        return $estudiante;
    }
        
    /*
     * function to add new estudiante
     */
    function add_estudiante($params)
    {
        $this->db->insert('estudiante',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update estudiante
     */
    function update_estudiante($estudiante_id,$params)
    {
        $this->db->where('estudiante_id',$estudiante_id);
        return $this->db->update('estudiante',$params);
    }
    
    /*
     * function to delete estudiante
     */
    function delete_estudiante($estudiante_id)
    {
        return $this->db->delete('estudiante',array('estudiante_id'=>$estudiante_id));
    }
}
