<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Grupo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get grupo by grupo_id
     */
    function get_grupo($grupo_id)
    {
        $grupo = $this->db->query("
            SELECT
                *

            FROM
                `grupo`

            WHERE
                `grupo_id` = ?
        ",array($grupo_id))->row_array();

        return $grupo;
    }
    
    /*
     * Get all grupo count
     */
    function get_all_grupo_count()
    {
        $grupo = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `grupo`
        ")->row_array();

        return $grupo['count'];
    }
        
    /*
     * Get all grupo
     */
    function get_all_grupo()
    {
        $grupo = $this->db->query("
            SELECT
                *

            FROM
                `grupo`

            WHERE
                1 = 1

            ORDER BY `grupo_id` DESC
            
        ")->result_array();

        return $grupo;
    }
        
    /*
     * function to add new grupo
     */
    function add_grupo($params)
    {
        $this->db->insert('grupo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update grupo
     */
    function update_grupo($grupo_id,$params)
    {
        $this->db->where('grupo_id',$grupo_id);
        return $this->db->update('grupo',$params);
    }
    
    /*
     * function to delete grupo
     */
    function delete_grupo($grupo_id)
    {
        return $this->db->delete('grupo',array('grupo_id'=>$grupo_id));
    }
    /*
     * Get all grupos de docente
     */
    function get_allgrupo_docente($docente_id)
    {
        $grupo = $this->db->query("
            SELECT
                g.grupo_nombre, p.periodo_horainicio, p.periodo_horafin,
                di.dia_nombre, a.aula_nombre, concat(ge.gestion_semestre, ' ', ge.gestion_descripcion) as descripcion_gestion,
                concat(d.docente_apellidos, ' ', d.docente_nombre) as nombre_docente, m.materia_nombre, u.usuario_nombre
            FROM
                grupo g
            LEFT JOIN horario h  on h.horario_id = g.horario_id
            LEFT JOIN periodo p  on p.periodo_id = h.horario_id
            LEFT JOIN dia     di on di.dia_id = h.dia_id
            LEFT JOIN aula    a  on a.aula_id = h.aula_id
            LEFT JOIN docente d  on d.docente_id = g.docente_id
            LEFT JOIN gestion ge on ge.gestion_id = g.gestion_id
            LEFT JOIN usuario u  on u.usuario_id = g.usuario_id
            LEFT JOIN materia m on m.materia_id = g.materia_id
            where
                d.docente_id = $docente_id
            
        ")->result_array();

        return $grupo;
    }
}
