<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Grupo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get grupo by grupo_id
     */
    function get_grupo($grupo_id)
    {
        $grupo = $this->db->query("
            SELECT
                *

            FROM
                `grupo`

            WHERE
                `grupo_id` = ?
        ",array($grupo_id))->row_array();

        return $grupo;
    }
    
    /*
     * Get all grupo count
     */
    function get_all_grupo_count()
    {
        $grupo = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `grupo`
        ")->row_array();

        return $grupo['count'];
    }
        
    /*
     * Get all grupo
     */
    function get_all_grupo($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $grupo = $this->db->query("
            SELECT
                *

            FROM
                `grupo`

            WHERE
                1 = 1

            ORDER BY `grupo_id` DESC

            " . $limit_condition . "
        ")->result_array();

        return $grupo;
    }
        
    /*
     * function to add new grupo
     */
    function add_grupo($params)
    {
        $this->db->insert('grupo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update grupo
     */
    function update_grupo($grupo_id,$params)
    {
        $this->db->where('grupo_id',$grupo_id);
        return $this->db->update('grupo',$params);
    }
    
    /*
     * function to delete grupo
     */
    function delete_grupo($grupo_id)
    {
        return $this->db->delete('grupo',array('grupo_id'=>$grupo_id));
    }
}
