<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Horario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get horario by horario_id
     */
    function get_horario($horario_id)
    {
        $horario = $this->db->query("
            SELECT
                *

            FROM
                `horario`

            WHERE
                `horario_id` = ?
        ",array($horario_id))->row_array();

        return $horario;
    }

    public function get_horario2($horario_id)
    {
        $this->db->select('*');
        $this->db->from('horario');
        $this->db->join('periodo', 'horario.periodo_id = periodo.periodo_id');
        $this->db->where('horario_id', $horario_id);
        $this->db->limit(1);
        $query = $this->db->get();

        if ($query->num_rows() == 1) {
            return $query->row();
        } else {
            return false;
        }
    }
    
    /*
     * Get all horario count
     */
    function get_all_horario_count()
    {
        $horario = $this->db->query("
            SELECT
                count(*) as count

            FROM
                `horario`
        ")->row_array();

        return $horario['count'];
    }
        
    /*
     * Get all horario
     */
    function get_all_horario($params = array())
    {
        $limit_condition = "";
        if(isset($params) && !empty($params))
            $limit_condition = " LIMIT " . $params['offset'] . "," . $params['limit'];
        
        $horario = $this->db->query("
            SELECT  * FROM  `horario`
            WHERE  1 = 1
            ORDER BY `horario_id` DESC

            " . $limit_condition . "
        ")->result_array();

        return $horario;
    }

    public function get_all_horarios($params=array())
    {
        $limit_condition = "";

        $this->db->select('*');
        $this->db->from('horario');
        $this->db->join('periodo', 'horario.periodo_id = periodo.periodo_id');
        $this->db->order_by("horario_id", "ASC");

        if(isset($params) && !empty($params)){
            $this->db->limit($params['limit'], $params['offset']);
        }

        $query = $this->db->get();
        return $query->result();
    }


        
    /*
     * function to add new horario
     */
    function add_horario($params)
    {
        $this->db->insert('horario',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update horario
     */
    function update_horario($horario_id,$params)
    {
        $this->db->where('horario_id',$horario_id);
        return $this->db->update('horario',$params);
    }
    
    /*
     * function to delete horario
     */
    function delete_horario($horario_id)
    {
        return $this->db->delete('horario',array('horario_id'=>$horario_id));
    }
}
