<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kardex_economico_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get kardex_economico by kardexeco_id
     */
    function get_kardex_economico($kardexeco_id)
    {
        $kardex_economico = $this->db->query("
            SELECT
                *

            FROM
                `kardex_economico`

            WHERE
                `kardexeco_id` = ?
        ",array($kardexeco_id))->row_array();

        return $kardex_economico;
    }
        
    /*
     * Get all kardex_economico
     */
    function get_all_kardex_economico()
    {
        $kardex_economico = $this->db->query("
            SELECT
                *

            FROM
                `kardex_economico`

            WHERE
                1 = 1

            ORDER BY `kardexeco_id` DESC
        ")->result_array();

        return $kardex_economico;
    }

    function get_kardex_est($dato)
    {
        $kardex_economico = $this->db->query("
            SELECT
                e.*

            FROM
                estudiante e

            WHERE
                e.estado_id=1
                and ".$dato."

            ORDER BY `estudiante_id` DESC
        ")->result_array();

        return $kardex_economico;
    }

    function get_est_kardex($dato)
    {
        $kardex_economico = $this->db->query("
            SELECT
                i.*, ke.*, c.*, e.*, n.*, g.*, es.*, ke.estado_id as 'elestado'

            FROM
                inscripcion i

            LEFT JOIN kardex_economico ke ON i.inscripcion_id=ke.inscripcion_id
            LEFT JOIN carrera c ON i.carrera_id=c.carrera_id
            LEFT JOIN estudiante e ON i.estudiante_id=e.estudiante_id
            LEFT JOIN nivel n ON i.nivel_id=n.nivel_id
            LEFT JOIN gestion g ON i.gestion_id=g.gestion_id
            LEFT JOIN estado es ON ke.estado_id=es.estado_id

            WHERE
                ke.estado_id = 1 
                 ".$dato."

            ORDER BY `kardexeco_id` DESC
        ")->result_array();

        return $kardex_economico;
    }

    function get_carrera_kardex($dato)
    {
        $kardex_economico = $this->db->query("
            SELECT
                n.nivel_id, pa.planacad_id, c.*, m.materia_id, g.*

            FROM
                nivel n, plan_academico pa, carrera c, materia m, grupo g

            WHERE
                m.materia_id=g.materia_id
                and m.nivel_id=n.nivel_id
                and n.planacad_id=pa.planacad_id
                and pa.carrera_id=c.carrera_id
                and ".$dato."

            ORDER BY `grupo_id` DESC
        ")->result_array();

        return $kardex_economico;
    }

    function get_datos_kardex($kardex_economico)
    {
        $kardex_economico = $this->db->query("
            SELECT
                i.*, ke.*, c.*, e.*

            FROM
                inscripcion i, kardex_economico ke, carrera c, estudiante e

            WHERE
                i.inscripcion_id=ke.inscripcion_id
                and i.carrera_id=c.carrera_id
                and ke.kardexeco_id= ".$kardex_economico."
                and i.estudiante_id=e.estudiante_id

            ORDER BY `kardexeco_id` DESC
        ")->result_array();

        return $kardex_economico;
    }
        
    /*
     * function to add new kardex_economico
     */
    function add_kardex_economico($params)
    {
        $this->db->insert('kardex_economico',$params);
        return $this->db->insert_id();
    }

    function registrar_kardex($sql)
    {
//        $this->db->insert('kardex_economico',$params);
        $this->db->query($sql);
        return $this->db->insert_id();

    }
    
    /*
     * function to update kardex_economico
     */
    function update_kardex_economico($kardexeco_id,$params)
    {
        $this->db->where('kardexeco_id',$kardexeco_id);
        return $this->db->update('kardex_economico',$params);
    }
    
    /*
     * function to delete kardex_economico
     */
    function delete_kardex_economico($kardexeco_id)
    {
        return $this->db->delete('kardex_economico',array('kardexeco_id'=>$kardexeco_id));
    }
    
    function get_kardex_economico_frominscripcion($inscripcion_id)
    {
        $kardex_academico = $this->db->query("
            SELECT
                k.kardexeco_id
            FROM
                `kardex_economico` k
            WHERE
                k.inscripcion_id = ?
        ",array($inscripcion_id))->row_array();

        return $kardex_academico['kardexeco_id'];
    }
    /* kardex economico dado una inscripcion */
    function get_keconomico_frominscripcion($inscripcion_id)
    {
        $kardex_economico = $this->db->query("
            SELECT
                k.*
            FROM
                `kardex_economico` k
            WHERE
                k.inscripcion_id = ?
        ",array($inscripcion_id))->row_array();

        return $kardex_economico;
    }
}
