<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Materia_asignada_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get materia_asignada by materiaasig_id
     */
    function get_materia_asignada($materiaasig_id)
    {
        $materia_asignada = $this->db->query("
            SELECT
                *

            FROM
                `materia_asignada`

            WHERE
                `materiaasig_id` = ?
        ",array($materiaasig_id))->row_array();

        return $materia_asignada;
    }
        
    /*
     * Get all materia_asignada
     */
    function get_all_materia_asignada()
    {
        $materia_asignada = $this->db->query("
            SELECT
                *

            FROM
                `materia_asignada`

            WHERE
                1 = 1

            ORDER BY `materiaasig_id` DESC
        ")->result_array();

        return $materia_asignada;
    }
        
    /*
     * function to add new materia_asignada
     */
    function add_materia_asignada($params)
    {
        $this->db->insert('materia_asignada',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update materia_asignada
     */
    function update_materia_asignada($materiaasig_id,$params)
    {
        $this->db->where('materiaasig_id',$materiaasig_id);
        return $this->db->update('materia_asignada',$params);
    }
    
    /*
     * function to delete materia_asignada
     */
    function delete_materia_asignada($materiaasig_id)
    {
        return $this->db->delete('materia_asignada',array('materiaasig_id'=>$materiaasig_id));
    }
    
    function get_materia_asignada_frominscripcion($kardexacad_id)
    {
        $materiaasig = $this->db->query("
            SELECT
                m.materiaasig_id
            FROM
                `materia_asignada` m
            WHERE
                m.kardexacad_id = ?
        ",array($kardexacad_id))->result_array();

        return $materiaasig;
    }
}
