<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Materia_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get materia by materia_id
     */
    function get_materia($materia_id)
    {
        $materia = $this->db->query("
            SELECT
                *

            FROM
                `materia`

            WHERE
                `materia_id` = ?
        ",array($materia_id))->row_array();

        return $materia;
    }
        
    /*
     * Get all materia
     */
    function get_all_materia()
    {
        $materia = $this->db->query("
            SELECT
                *

            FROM
                `materia`

            WHERE
                1 = 1

            ORDER BY `materia_id` DESC
        ")->result_array();

        return $materia;
    }
        
    /*
     * function to add new materia
     */
    function add_materia($params)
    {
        $this->db->insert('materia',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update materia
     */
    function update_materia($materia_id,$params)
    {
        $this->db->where('materia_id',$materia_id);
        return $this->db->update('materia',$params);
    }
    
    /*
     * function to delete materia
     */
    function delete_materia($materia_id)
    {
        return $this->db->delete('materia',array('materia_id'=>$materia_id));
    }
}
