<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Material_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
    *Obtener todo el material de una materia
    */
    function get_all_material($docente_id ,$materia_id){
        $material = $this->db->query(
        "SELECT me.*, e.`estado_descripcion`
        FROM material_estudio AS me
        LEFT JOIN horario AS h ON h.`docente_id` = me.`docente_id`
        LEFT JOIN grupo AS g ON g.`grupo_id` = h.`grupo_id`
        LEFT JOIN materia AS m ON m.materia_id =  me.`materia_id`
        LEFT JOIN estado AS e ON e.`estado_id` = me.`estado_id`
        WHERE me.`docente_id` = $docente_id
        AND me.`materia_id` = $materia_id
        GROUP BY me.`materialest_id`
        ")->result_array();

        return $material;
    }

    /*
    * estados
    */
    function get_estado(){
        $estados = $this->db->query(
        'SELECT * FROM estado WHERE estado_tipo = 1'
        )->result_array();
        return $estados;
    }

    /* 
    * Añadir material 
    */
    function add_material($params){
        $this->db->insert('material_estudio',$params);
        return $this->db->insert_id();
    }

    /*
    * Actualizar material 
    */
    function update_material($material_id, $params){
        $this->db->where('materialest_id',$material_id);
        return $this->db->update('material_estudio',$params);
    }
    
    /*
    *   Obtener material 
    */
    function get_material($materialest_id){
        $material = $this->db->query(
            "SELECT *
            FROM material_estudio 
            WHERE materialest_id = $materialest_id
            "
            )->row_array();

        return $material;
    }
}
