<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Materia_kardex_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
        
    /*
     * function to add new materia_asignada
     */
    function add_materia_kardex($params)
    {
        $this->db->insert('materia_kardex',$params);
        return $this->db->insert_id();
    }
    
}
