<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Matricula_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get matricula by matricula_id
     */
    function get_matricula($matricula_id)
    {
        $matricula = $this->db->query("
            SELECT
                *

            FROM
                `matricula`

            WHERE
                `matricula_id` = ?
        ",array($matricula_id))->row_array();

        return $matricula;
    }
        
    /*
     * Get all matricula
     */
    function get_all_matricula()
    {
        $matricula = $this->db->query("
            SELECT
                *

            FROM
                `matricula`

            WHERE
                1 = 1

            ORDER BY `matricula_id` DESC
        ")->result_array();

        return $matricula;
    }
        
    /*
     * function to add new matricula
     */
    function add_matricula($params)
    {
        $this->db->insert('matricula',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update matricula
     */
    function update_matricula($matricula_id,$params)
    {
        $this->db->where('matricula_id',$matricula_id);
        return $this->db->update('matricula',$params);
    }
    
    /*
     * function to delete matricula
     */
    function delete_matricula($matricula_id)
    {
        return $this->db->delete('matricula',array('matricula_id'=>$matricula_id));
    }
    function get_matricula_frominscripcion($inscripcion_id)
    {
        $matricula = $this->db->query("
            SELECT
                m.matricula_id
            FROM
                `matricula` m
            WHERE
                m.inscripcion_id = ?
        ",array($inscripcion_id))->row_array();

        return $matricula['matricula_id'];
    }
}
