<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mensualidad_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get mensualidad by mensualidad_id
     */
    function get_mensualidad($mensualidad_id)
    {
        $mensualidad = $this->db->query("
            SELECT
                *

            FROM
                `mensualidad`

            WHERE
                `mensualidad_id` = ?
        ",array($mensualidad_id))->row_array();

        return $mensualidad;
    }
        
    /*
     * Get all mensualidad
     */
    function get_all_mensualidad()
    {
        $mensualidad = $this->db->query("
            SELECT
                *

            FROM
                `mensualidad`

            WHERE
                1 = 1

            ORDER BY `mensualidad_id` DESC
        ")->result_array();

        return $mensualidad;
    }
        
    /*
     * function to add new mensualidad
     */
    function add_mensualidad($params)
    {
        $this->db->insert('mensualidad',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update mensualidad
     */
    function update_mensualidad($mensualidad_id,$params)
    {
        $this->db->where('mensualidad_id',$mensualidad_id);
        return $this->db->update('mensualidad',$params);
    }
    
    /*
     * function to delete mensualidad
     */
    function delete_mensualidad($mensualidad_id)
    {
        return $this->db->delete('mensualidad',array('mensualidad_id'=>$mensualidad_id));
    }
}
