<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mensualidad_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get mensualidad by mensualidad_id
     */
    function get_mensualidad($mensualidad_id)
    {
        $mensualidad = $this->db->query("
            SELECT
                *

            FROM
                `mensualidad`

            WHERE
                `mensualidad_id` = ?
        ",array($mensualidad_id))->row_array();

        return $mensualidad;
    }

    function ejecutar($sql){
         
        $this->db->query($sql);
        return $this->db->insert_id();
    }
        
    /*
     * Get all mensualidad
     */
    function get_all_mensualidad()
    {
        $mensualidad = $this->db->query("
            SELECT
                *

            FROM
                `mensualidad`

            WHERE
                1 = 1

            ORDER BY `mensualidad_id` DESC
        ")->result_array();

        return $mensualidad;
    }

    function get_pendientes($kardex_id)
    {
        $mensualidad = $this->db->query("
            SELECT
                m.*

            FROM
               mensualidad m
            WHERE
             
                 m.kardexeco_id = ".$kardex_id." 
                 and m.estado_id = 8

            ORDER BY `mensualidad_id` ASC

          
        ")->result_array();

        return $mensualidad;
    }
    /* tambien se lo esta usando en modificar inscripcion */
    function kardex_mensualidad($kardex_id)
    {
        $mensualidad = $this->db->query("
            SELECT
                m.*, e.*, f.factura_id

            FROM
                mensualidad m

            LEFT JOIN estado e on m.estado_id=e.estado_id
            LEFT JOIN factura f on m.mensualidad_id = f.mensualidad_id
            WHERE
                 m.estado_id <> 27
                 and m.estado_id <> 3
                 and m.kardexeco_id = ".$kardex_id."

            ORDER BY m.mensualidad_numero, m.mensualidad_id  ASC
        ")->result_array();

        return $mensualidad;
    }

    function get_credito_cliente($kardexeco)
    {
        $credito = $this->db->query("
            SELECT
                ke.*, i.estudiante_id, e.cliente_id, v.cliente_id, c.*

            FROM
                kardex_economico ke

            LEFT JOIN inscripcion i on ke.inscripcion_id=i.inscripcion_id
            LEFT JOIN estudiante e on i.estudiante_id = e.estudiante_id
            LEFT JOIN venta v on e.cliente_id = v.cliente_id
            LEFT JOIN credito c on v.venta_id = c.venta_id

            WHERE ke.kardexeco_id=".$kardexeco."
            and c.estado_id = 8
        ")->result_array();

        return $credito;
    }
     function geta_mensualidades()
    {
        $mensualidad = $this->db->query("
            SELECT
                m.*, e.*,sum(m.mensualidad_montocancelado) as sux, max(m.mensualidad_fechapago) as fecha

            FROM
                mensualidad m , estado e

            WHERE
                m.estado_id=e.estado_id

             group by m.kardexeco_id, m.mensualidad_numero 
            
        ")->result_array();

        return $mensualidad;
    }
    function suma_mensualidades()
    {
        $mensualidad = $this->db->query("
           SELECT
                m.mensualidad_numero,m.kardexeco_id,sum(m.mensualidad_montocancelado) as sux, k.kardexeco_id 

            FROM
                mensualidad m, kardex_economico k
            WHERE
                m.kardexeco_id=k.kardexeco_id
            group by m.mensualidad_numero,m.kardexeco_id
        ")->result_array();

        return $mensualidad;
    }
    
    function boucher_mensualidad($mensualidad_id)
    {
        $mensualidad = $this->db->query("
            SELECT
                m.*, ke.*, i.*, e.*, c.*, u.usuario_nombre, g.*

            FROM
                mensualidad m, kardex_economico ke, inscripcion i, estudiante e, carrera c, usuario u, gestion g

            WHERE
                m.mensualidad_id= ".$mensualidad_id."
                and m.kardexeco_id=ke.kardexeco_id
                and ke.inscripcion_id = i.inscripcion_id
                and i.gestion_id = g.gestion_id
                and i.carrera_id = c.carrera_id
                and i.estudiante_id = e.estudiante_id
                and m.usuario_id = u.usuario_id

            ORDER BY `mensualidad_numero` ASC
        ")->result_array();

        return $mensualidad;
    }

    function grupo_mensualidad($grupo)
    {
        $mensualidad = $this->db->query("
            SELECT
                 c.*, g.*, i.inscripcion_id, gi.*, ke.*, e.*

            FROM
                grupo g
                
            LEFT JOIN grupo_inscripcion gi on g.grupo_id=gi.grupo_id
            LEFT JOIN inscripcion i on gi.inscripcion_id=i.inscripcion_id
            LEFT JOIN kardex_economico ke on ke.inscripcion_id = i.inscripcion_id
            LEFT JOIN carrera c on i.carrera_id = c.carrera_id
            LEFT JOIN estudiante e on i.estudiante_id = e.estudiante_id

            WHERE
                g.grupo_id=".$grupo."
                
            ORDER BY `estudiante_apellidos` DESC
        ")->result_array();

        return $mensualidad;
    }

   /* function get_pensiones($grupo,$estudiante)
    {
        foreach ($estudiante as $e ) {
            
       
         $mensualidad = $this->db->query("
            SELECT
                 c.*, g.*, i.inscripcion_id, gi.*, ke.*, e.*, m.*

            FROM
                carrera c, grupo g, inscripcion i, grupo_inscripcion gi, kardex_economico ke, estudiante e, mensualidad m

            WHERE
                g.grupo_id=".$grupo."
                and g.grupo_id=gi.grupo_id
                and gi.inscripcion_id=i.inscripcion_id
                and ke.inscripcion_id = i.inscripcion_id
                and ke.kardexeco_id = m.kardexeco_id
                and i.carrera_id = c.carrera_id
                and ".$e." = e.estudiante_id
                and i.estudiante_id = e.estudiante_id
                

            ORDER BY `estudiante_apellidos` DESC
        ")->result_array();

        return $mensualidad;
         }
    }*/

    function parcial_mensualidad($kardexeco_id,$descuento,$cancelado,$fechalimite,$mensualidad_fechalimite,$mensualidad_montoparcial,$mensualidad_numero,$usuario_id,$mes)
    {
        $mensualidad ="INSERT INTO mensualidad (kardexeco_id,usuario_id,estado_id,mensualidad_numero,mensualidad_descuento,mensualidad_montocancelado,mensualidad_montoparcial,mensualidad_montototal,mensualidad_fechalimite,mensualidad_mes) VALUES (".$kardexeco_id.",".$usuario_id.",8,".$mensualidad_numero.",".$descuento.",".$cancelado.",".$mensualidad_montoparcial.",".$mensualidad_montoparcial.",".$mensualidad_fechalimite.",'".$mes."')";
                $this->db->query($mensualidad);
    }
        
    /*
     * function to add new mensualidad
     */
    function add_mensualidad($params)
    {
        $this->db->insert('mensualidad',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update mensualidad
     */
    function update_mensualidad($mensualidad_id,$params)
    {
        $this->db->where('mensualidad_id',$mensualidad_id);
        return $this->db->update('mensualidad',$params);
    }

    function numero($gestion_id)
    {
        $num = $this->db->query("
            select g.`gestion_numingreso`
            from gestion g
            where g.gestion_id = $gestion_id
        ")->result_array();
        return $num;
    }
    
    /*
     * function to delete mensualidad
     */
    function delete_mensualidad($mensualidad_id)
    {
        return $this->db->delete('mensualidad',array('mensualidad_id'=>$mensualidad_id));
    }
    /*
     * function to delete mensualidades de un kardex economico
     * de los que no fueron cancelados
     */
    function delete_menskardexeco($kardexeco_id)
    {
        $mensualidad = $this->db->query("
            DELETE FROM
                `mensualidad`
            WHERE
                estado_id <> 9
                and kardexeco_id = $kardexeco_id 
                
       ");
        /*$this->db->query($mensualidad);
        return $mensualidad;
        $this->db->where('mensualidad_inscripcionpago', 0);
        $this->db->where('estado_id', 8);
        $this->db->or_where('estado_id', 3);
        $this->db->where('kardexeco_id', $kardexeco_id);
        return $this->db->delete('mensualidad');*/
        //return $this->db->delete('mensualidad',array('kardexeco_id'=>$kardexeco_id));
    }
    /*
     * function que anula mensualidades que hayan sido canceladas para ponerlos en anuladas
     * de un determinado kardex economico para asi no perder el registro de numero de ingreso
     */
    function anular_mensualidad($kardexeco_id,$params)
    {
        $this->db->where('kardexeco_id',$kardexeco_id);
        return $this->db->update('mensualidad',$params);
    }
    
    function get_mensualidad_frominscripcion($kardexeco_id)
    {
        $mensualidad = $this->db->query("
            SELECT
                m.mensualidad_id
            FROM
                `mensualidad` m
            WHERE
                m.kardexeco_id = ?
        ",array($kardexeco_id))->result_array();

        return $mensualidad;
    }
    /* obtiene el numero de mensualidades pagadas en el momento de la inscripcion,
     * se lo usa en editar inscripcion
     */
    function get_menspagada_inscripcion($kardexeco_id)
    {
        $mensualidad = $this->db->query("
            SELECT
                count(m.mensualidad_inscripcionpago) as pagados
            FROM
               mensualidad m
            WHERE
                 m.mensualidad_inscripcionpago = 1
                 and m.estado_id = 9
                 and m.kardexeco_id = ".$kardexeco_id." 
        ")->row_array();
        return $mensualidad;
    }
}
