<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Notum_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get notum by nota_id
     */
    function get_notum($nota_id)
    {
        $notum = $this->db->query("
            SELECT
                *

            FROM
                `nota`

            WHERE
                `nota_id` = ?
        ",array($nota_id))->row_array();

        return $notum;
    }
        
    /*
     * Get all nota
     */
    function get_all_nota()
    {
        $nota = $this->db->query("
            SELECT
                *

            FROM
                `nota`

            WHERE
                1 = 1

            ORDER BY `nota_id` DESC
        ")->result_array();

        return $nota;
    }
        
    /*
     * function to add new notum
     */
    function add_notum($params)
    {
        $this->db->insert('nota',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update notum
     */
    function update_notum($nota_id,$params)
    {
        $this->db->where('nota_id',$nota_id);
        return $this->db->update('nota',$params);
    }
    
    /*
     * function to delete notum
     */
    function delete_notum($nota_id)
    {
        return $this->db->delete('nota',array('nota_id'=>$nota_id));
    }
}
