<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Periodo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get periodo by periodo_id
     */
    function get_periodo($periodo_id)
    {
        $periodo = $this->db->query("
            SELECT
                *

            FROM
                `periodo`

            WHERE
                `periodo_id` = ?
        ",array($periodo_id))->row_array();

        return $periodo;
    }
        
    /*
     * Get all periodo
     */
    function get_all_periodo()
    {
        $periodo = $this->db->query("
            SELECT
                *

            FROM
                `periodo`

            WHERE
                1 = 1

            ORDER BY `periodo_id` DESC
        ")->result_array();

        return $periodo;
    }
        
    /*
     * function to add new periodo
     */
    function add_periodo($params)
    {
        $this->db->insert('periodo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update periodo
     */
    function update_periodo($periodo_id,$params)
    {
        $this->db->where('periodo_id',$periodo_id);
        return $this->db->update('periodo',$params);
    }
    
    /*
     * function to delete periodo
     */
    function delete_periodo($periodo_id)
    {
        return $this->db->delete('periodo',array('periodo_id'=>$periodo_id));
    }
}
