<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Plan_academico_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get plan_academico by plan_academico_id
     */
    function get_plan_academico($plan_academico_id)
    {
        $plan_academico = $this->db->query("
            SELECT
                *

            FROM
                `plan_academico`

            WHERE
                `plan_academico_id` = ?
        ",array($plan_academico_id))->row_array();

        return $plan_academico;
    }
        
    /*
     * Get all plan_academico
     */
    function get_all_plan_academico()
    {
        $plan_academico = $this->db->query("
            SELECT
                *

            FROM
                `plan_academico`

            WHERE
                1 = 1

            ORDER BY `plan_academico_id` DESC
        ")->result_array();

        return $plan_academico;
    }
        
    /*
     * function to add new plan_academico
     */
    function add_plan_academico($params)
    {
        $this->db->insert('plan_academico',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update plan_academico
     */
    function update_plan_academico($plan_academico_id,$params)
    {
        $this->db->where('plan_academico_id',$plan_academico_id);
        return $this->db->update('plan_academico',$params);
    }
    
    /*
     * function to delete plan_academico
     */
    function delete_plan_academico($plan_academico_id)
    {
        return $this->db->delete('plan_academico',array('plan_academico_id'=>$plan_academico_id));
    }
}
